choco install winrar
choco install vlc /y
choco install foxitreader /y
choco install ditto /y
choco install ditto.install /y
choco install greenshot /y
choco install screentogif /y
choco install notepadplusplus /y
choco install notepadplusplus.install /y
choco install docker /y
choco install docker-for-windows /y
choco install DotNet4.5 /y
choco install DotNet4.5.2 /y
choco install DotNet4.6.1 /y
choco install FiraCode /y
choco install Firefox /y
choco install git /y
choco install git-credential-manager-for-windows /y
choco install git.install /y
choco install handle /y
choco install ilspy /y
choco install MarkdownMonster /y
choco install nodejs /y
choco install nodejs.install /y
choco install poshgit /y
choco install vscode /y
choco install conemu /y
choco install p4merge /y